In [2]:
import numpy as np

In [11]:
# Random stuff
# creates an array containing random numbers drawn from an uniform distribution on the interval [0, 1)
# creates 2 arrays containing 3 numbers
np.random.rand(2,3)


array([[0.05887193, 0.89534594, 0.72920833],
       [0.52389611, 0.59535201, 0.85315018]])

In [16]:
# creates three arrays containing 2 numbers
np.random.rand(3,2)

array([[0.80723264, 0.62613445],
       [0.15148645, 0.2974689 ],
       [0.27848519, 0.70140761]])

In [25]:
a = np.random.rand(3,2)
a[1][1]

0.9590173298253566

In [26]:
# randn for normal distribution

np.random.random_sample(3)

array([0.34665689, 0.53240357, 0.25763181])

In [28]:
# distributions:
# np.random.normal()
# np.random.binomial()
# std.norm.dist with mean 0 and var 1
np.random.normal(0,1)

# draw 5 numbers from a normal distribution with mean 0 and var 1
np.random.normal(0,1,5)

array([ 0.52740529, -1.40280588, -1.65800118, -2.83821468, -0.59994094])

In [30]:
# linalg stuff
X = np.array([[1,2],[3,4]])
# calculates the inverse (in contrast to R´s solve. solve here means solving ax = b, instead of inverting the matrix)
np.linalg.inv(X)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [40]:
y = np.array([1,2])
# calculates the dot product of X and y with @
# lse for linear regression
np.linalg.inv((np.transpose(X) @ X)) @ np.transpose(X) @ y

array([1., 2.])

In [42]:
def lse(X, y):
    return np.linalg.inv((np.transpose(X) @ X)) @ np.transpose(X) @ y

In [43]:
def mse(X, y):
    return np.mean((y - lse(X, y))**2)

In [44]:
def rmse(X, y):
    return np.sqrt(mse(X, y))

In [47]:
X = np.array([[1,2],[1,4]])
y = np.array([1,2])
rmse(X, y)

1.274754878398196

In [51]:
# seed with. But is it working through all the code?
np.random.seed(1337)
np.random.randint(0,10)

7

In [52]:
np.random.seed(1337)
np.random.randint(0,10)
# it does work through all the code

7

In [54]:
# matrices
# creates a matrix with 3 rows and 2 columns
np.zeros((3,2))
# bind rows 
np.concatenate((np.zeros((3,2)), np.ones((3,2))), axis = 0)
# bind columns
np.concatenate((np.zeros((3,2)), np.ones((3,2))), axis = 1)
# by defining axis = 0 or axis = 1, the matrix is stacked vertically or horizontally
# so axis = 0 binds rows, axis = 1 binds columns

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [64]:
np.ones(2)
# np.linalg.det for determinant
np.linalg.det(np.ones((2,2)))
# create a diagonal matrix with ones on the diagonal
np.eye(2)
# is the same as
np.eye(2,2)

array([[1., 0.],
       [0., 1.]])

In [68]:
# dimensions
X.shape
# access with
X.shape[0]


2

In [72]:
for x,y in zip(X, y):
    print(x)
    print(y)

[1 2]
1
[1 4]
2


In [73]:
# vector
np.array([[3],[4]])
# 1x2 Matrix
np.array([[1,2]])

np.dot(np.array([[1,2]]), np.array([[3],[4]]))
# same as
np.array([[1,2]]) @ np.array([[3],[4]])

array([[11]])

In [15]:
x = np.array([[1,2],[3,4], [5,6], [7,8]])
y = np.array([1,2])
for xi, y in zip(x,y):
    print(xi)
    print(y)

[1 2]
1
[3 4]
2


In [18]:
print(np.array([1,2]))
print(np.array([[1,2], [3,4]]))

[1 2]
[[1 2]
 [3 4]]


array([[1, 2],
       [1, 4]])